line_length:
- 260 # warning
- 300 # error
excluded:
- Pods
force_cast: warning
force_try:
  severity: warning # explicitly
disabled_rules:
- force_cast
- force_try
function_body_length:
- 70 # warning
- 100 # error
cyclomatic_complexity:
- 11 # warning
- 20 # error
